### PR TITLE
Feature Request: Private Replies

### PR DESCRIPTION
**Pull request by aMahanna**
image
image

### CODE REVIEW

**Comment by aMahanna** [comment]
https://github.com/ieee-uottawa/SITE-Bot/blob/acb68dffd910f3ac75551de39914dc32b5bcde75/commands/contribute.ts#L15-L19

A more "restrictive" alternative to this would be the following: 

image

Right now, if a user types `!help publicATypoHere`, it will still register the command as public (maybe we want this though)

**Comment by RyanFleck** [comment]
I'll run now.

**Review by RyanFleck — DISMISSED** [review]
LGTM!

**Review by RyanFleck — APPROVED** [review]
Had to make a small addition, still lgtm. 

Congrats @aMahanna on the first contribution to the bot :)

**Pull request merged**
